---
id: sezemi-2015-oss-hack-weekend-overview2
base_name: where-we-go
tags:
- rabbit
- sezemi
- oss
presentation_date: 2015-07-12
version: 2015.7.12.1
licenses:
- CC BY-SA 4.0
slideshare_id: sezemi-2015-oss-hack-weekend-overview2
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :rd
  name: Kouhei Sutou
  email: kou@clear-code.com
  rubygems_user: kou
  slideshare_user: kou
  speaker_deck_user: kou
