---
id: sezemi-2015-oss-hack-weekend-overview1
base_name: how-to-start-oss-development
tags:
- rabbit
- sezemi
- oss
presentation_date: 2015-07-11
version: 2015.7.11.0
licenses:
- CC BY-SA 4.0
slideshare_id: sezemi-2015-oss-hack-weekend-overview1
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :rd
  name: Kouhei Sutou
  email: kou@clear-code.com
  rubygems_user: kou
  slideshare_user: kou
  speaker_deck_user: kou
