---
id: readable-code-tsukuba-conclusion
base_name: next-step
tags:
- rabbit
- readable-code
- sezemi
presentation_date: 2015-07-04
version: 2015.7.4.1
licenses:
- CC BY-SA 4.0
slideshare_id: readable-code-tsukuba-conclusion
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :rd
  name: Kouhei Sutou
  email: kou@clear-code.com
  rubygems_user: kou
  slideshare_user: kou
  speaker_deck_user: kou
