---
id: sezemi-2015-oss-hack-4-beginners-conclusion
base_name: next-step
tags:
- rabbit
- sezemi
- oss
presentation_date: 2015-06-27
version: 2015.6.27.2
licenses:
- CC BY-SA 4.0
slideshare_id: sezemi-2015-oss-hack-4-beginners-conclusion
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :rd
  name: Kouhei Sutou
  email: kou@clear-code.com
  rubygems_user: kou
  slideshare_user: kou
  speaker_deck_user: kou
